version: '3'
services:
  jenkins:
    container_name: 'myjenkins'
    image: 'myjenkins:latest'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'myjenkins-data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '8080:8080'

volumes:
  myjenkins-data:
    external: false
